jobs:
- name: tests-master
  plan:
  - do:
    - aggregate:
      - get: docker-image
        passed: [build-task-image]
        params: {rootfs: true}
        trigger: true
      - get: airmarshal
        resource: git-airmarshal
        trigger: true
      - get: airmarshal-concourse
        resource: git-airmarshal-concourse
        trigger: true
    - task: run-tests
      config:
        platform: linux
        image: docker:///starkandwaynebot/airmarshal-pipeline
        inputs:
        - { name: airmarshal }
        - { name: airmarshal-concourse }
        - { name: docker-image }
        run:
          path: ./airmarshal-concourse/scripts/run-tests
          args: []

- name: tests-dev
  plan:
  - do:
    - aggregate:
      - get: docker-image
        passed: [build-task-image]
        params: {rootfs: true}
        trigger: true
      - get: airmarshal
        resource: git-airmarshal-dev
        trigger: true
      - get: airmarshal-concourse
        resource: git-airmarshal-concourse
        trigger: true
    - task: run-tests
      config:
        platform: linux
        image: docker:///starkandwaynebot/airmarshal-pipeline
        inputs:
        - { name: airmarshal }
        - { name: airmarshal-concourse }
        - { name: docker-image }
        run:
          path: ./airmarshal-concourse/scripts/run-tests
          args: []
        params:

- name: build-task-image
  public: true
  serial: true
  plan:
  - get: git-airmarshal-concourse-image
    trigger: true
  - put: docker-image
    params:
      build: git-airmarshal-concourse-image/ci-image

resources:
- name: git-airmarshal
  type: git
  source:
    uri: git@github.com:mkb/airmarshal.git
    private_key: {{private-key}}
    branch: master

- name: git-airmarshal-dev
  type: git
  source:
    uri: https://github.com/starkandwayne/airmarshal.git
    branch: develop

- name: git-airmarshal-concourse
  type: git
  source:
    uri: https://github.com/starkandwayne/airmarshal-concourse.git
    branch: master
    ignore_paths:
    - ci-image/*

- name: git-airmarshal-concourse-image
  type: git
  source:
    uri: https://github.com/starkandwayne/airmarshal-concourse.git
    branch: master
    paths:
    - ci-image/*

- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: starkandwaynebot
    password: {{docker-hub-password}}
    repository: starkandwaynebot/airmarshal-pipeline
